In [50]:
import pandas as pd

In [51]:
import numpy as np

In [52]:
#Load the Raw CSV

In [53]:
df1=pd.read_csv(r"D:\DATA ANALYSIS\E-commerce Funnel & RFM\Data\raw\online_retail_1.csv")
df1

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009/12/01 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009/12/01 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009/12/01 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009/12/01 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009/12/01 7:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010/12/09 20:01,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010/12/09 20:01,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010/12/09 20:01,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010/12/09 20:01,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010/12/09 20:01,1.95,17530.0,United Kingdom

In [54]:
df2=pd.read_csv(r"D:\DATA ANALYSIS\E-commerce Funnel & RFM\Data\raw\online_retail_2.csv")
df2

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010/12/01 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010/12/01 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010/12/01 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010/12/01 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010/12/01 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011/12/09 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011/12/09 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011/12/09 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011/12/09 12:50,4.95,12680.0,France
541909,581587,POST,POSTAGE,1,2011/12/09 12:50,18.00,12680.0,France

In [55]:
df=pd.concat([df1, df2], ignore_index=True)
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009/12/01 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009/12/01 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009/12/01 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009/12/01 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009/12/01 7:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011/12/09 12:50,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011/12/09 12:50,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011/12/09 12:50,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011/12/09 12:50,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011/12/09 12:50,18.00,12680.0,France

In [56]:
df.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009/12/01 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009/12/01 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009/12/01 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009/12/01 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009/12/01 7:45,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009/12/01 7:45,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009/12/01 7:45,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009/12/01 7:45,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009/12/01 7:46,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009/12/01 7:46,3.75,13085.0,United Kingdom

In [57]:
#Inspect Columns and Data Types

In [58]:
print("Column names:")
print(df.columns.tolist())

Column names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [59]:
print("\nData types:")
print(df.dtypes)

Data types:
Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

In [60]:
print("\nBasic info:")
df.info()

Basic info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [61]:
#Check Missing Values

In [62]:
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [63]:
print("\nMissing percentage:")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing percentage:
Invoice         0.00
StockCode       0.00
Description     0.41
Quantity        0.00
InvoiceDate     0.00
Price           0.00
Customer ID    22.77
Country         0.00
dtype: float64

In [64]:
#Check Duplicates

In [65]:
duplicates=df.duplicated().sum()
print(f"Duplicates Rows:{duplicates}")
print(f"Total Rows before dedup:{len(df)}")

Duplicates Rows:34335
Total Rows before dedup:1067371

In [66]:
# Invoices starting with 'C' are cancellations

In [67]:
cancellations = df[df['Invoice'].astype(str).str.startswith('C')]
print(f"Cancellation rows: {len(cancellations)}")
print(f"Cancellation percentage: {len(cancellations)/len(df)*100:.2f}%")

print("\nSample cancellations:")
cancellations.head(3)

Cancellation rows: 19494
Cancellation percentage: 1.83%

Sample cancellations:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009/12/01 10:33,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009/12/01 10:33,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009/12/01 10:33,4.25,16321.0,Australia

In [68]:
#Explore Non-Product StockCodes

In [69]:
non_products = df[df['StockCode'].astype(str).str.match(r'^(POST|DOT|M|D|C2|BANK CHARGES|B|PADS|CRUK|TEST)', na=False)]
print(f"Non-product rows: {len(non_products)}")
print("\nUnique non-product StockCodes:")
print(non_products['StockCode'].unique())

Non-product rows: 5766

Unique non-product StockCodes:
['POST' 'D' 'DCGS0058' 'DCGS0068' 'DOT' 'M' 'DCGS0004' 'DCGS0076' 'C2'
 'BANK CHARGES' 'DCGS0003' 'TEST001' 'DCGS0072' 'DCGS0044' 'TEST002'
 'DCGS0066N' 'PADS' 'DCGSSGIRL' 'DCGS0006' 'DCGS0016' 'DCGS0027'
 'DCGS0036' 'DCGS0039' 'DCGS0060' 'DCGS0056' 'DCGS0059' 'DCGSLBOY'
 'DCGS0053' 'DCGS0062' 'DCGS0037' 'DCGSSBOY' 'DCGSLGIRL' 'DCGS0069'
 'DCGS0070' 'DCGS0075' 'B' 'DCGS0041' 'DCGS0055' 'DCGS0074' 'DCGS0057'
 'DCGS0073' 'DCGS0071' 'DCGS0066P' 'DCGS0067' 'CRUK']

In [70]:
#Check Quantity and Price Ranges

In [71]:
print("Quantity stats:")
print(df['Quantity'].describe())

Quantity stats:
count    1.067371e+06
mean     9.938898e+00
std      1.727058e+02
min     -8.099500e+04
25%      1.000000e+00
50%      3.000000e+00
75%      1.000000e+01
max      8.099500e+04
Name: Quantity, dtype: float64

In [72]:
print("\nNegative quantities:", (df['Quantity'] < 0).sum())

Negative quantities: 22950

In [73]:
print("\nPrice stats:")
print(df['Price'].describe())

Price stats:
count    1.067371e+06
mean     4.649388e+00
std      1.235531e+02
min     -5.359436e+04
25%      1.250000e+00
50%      2.100000e+00
75%      4.150000e+00
max      3.897000e+04
Name: Price, dtype: float64

In [74]:
print("\nPrice <= 0:", (df['Price'] <= 0).sum())
print("Price == 0:", (df['Price'] == 0).sum())
print("Price < 0:", (df['Price'] < 0).sum())

Price <= 0: 6207
Price == 0: 6202
Price < 0: 5

In [75]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

print("Date range:")
print("Earliest:", df['InvoiceDate'].min())
print("Latest:", df['InvoiceDate'].max())
print("Days covered:", (df['InvoiceDate'].max() - df['InvoiceDate'].min()).days)

Date range:
Earliest: 2009-12-01 07:45:00
Latest: 2011-12-09 12:50:00
Days covered: 738

In [76]:
#Clean the Data

In [77]:
# Start with a copy so we don't lose the original
df_clean=df.copy()

In [78]:
# 1. Remove cancellations (Invoice starting with 'C')
df_clean=df_clean[~df_clean['Invoice'].astype(str).str.startswith('C')]

In [79]:
# 2. Remove missing Customer ID
df_clean = df_clean.dropna(subset=['Customer ID'])

In [80]:
# 3. Remove negative or zero quantity
df_clean = df_clean[df_clean['Quantity'] > 0]

In [81]:
# 4. Remove zero or negative price
df_clean = df_clean[df_clean['Price'] > 0]

In [82]:
# 5. Remove non-product StockCodes
non_product_codes = ['POST', 'DOT', 'M', 'D', 'C2', 'BANK CHARGES', 'B', 'PADS', 'CRUK', 'TEST']
df_clean = df_clean[~df_clean['StockCode'].astype(str).isin(non_product_codes)]

In [83]:
# 6. Remove duplicates
df_clean = df_clean.drop_duplicates()

In [84]:
# 7. Convert Customer ID to integer (no more decimals)
df_clean['Customer ID'] = df_clean['Customer ID'].astype(int)

In [85]:
# 8. Add TotalPrice column
df_clean['TotalPrice'] = round(df_clean['Quantity'] * df_clean['Price'],2)

In [86]:
print(f"Rows before cleaning: {len(df)}")
print(f"Rows after cleaning:  {len(df_clean)}")
print(f"Removed: {len(df) - len(df_clean)} rows ({(len(df)-len(df_clean))/len(df)*100:.2f}%)")

Rows before cleaning: 1067371
Rows after cleaning:  776624
Removed: 290747 rows (27.24%)

In [87]:
#Verify the Cleaned Data

In [88]:
print("Cleaned data shape:", df_clean.shape)
print("\nColumn types:")
print(df_clean.dtypes)

Cleaned data shape: (776624, 9)

Column types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             int64
Country                object
TotalPrice            float64
dtype: object

In [89]:
print("\nMissing values after cleaning:")
print(df_clean.isnull().sum())

Missing values after cleaning:
Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
TotalPrice     0
dtype: int64

In [90]:
print("\nSample cleaned rows:")
df_clean.head()

Sample cleaned rows:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [91]:
#Quick Sanity Check on Numbers

In [92]:
print("Summary of cleaned data:")
print(f"Unique customers: {df_clean['Customer ID'].nunique()}")
print(f"Unique invoices:  {df_clean['Invoice'].nunique()}")
print(f"Unique products:  {df_clean['StockCode'].nunique()}")
print(f"Total revenue:    £{df_clean['TotalPrice'].sum():,.2f}")
print(f"Date range:       {df_clean['InvoiceDate'].min()} to {df_clean['InvoiceDate'].max()}")

Summary of cleaned data:
Unique customers: 5861
Unique invoices:  36639
Unique products:  4624
Total revenue:    £17,073,078.29
Date range:       2009-12-01 07:45:00 to 2011-12-09 12:50:00

In [93]:
# 1. Add missing non-product codes
extra_non_products = ['TEST001', 'TEST002']
df_clean = df_clean[~df_clean['StockCode'].astype(str).isin(extra_non_products)]

In [94]:
# 2. Remove DCGS codes
df_clean = df_clean[~df_clean['StockCode'].astype(str).str.startswith('DCGS')]

In [95]:
# 3. Rename Customer ID column
df_clean = df_clean.rename(columns={'Customer ID': 'CustomerID'})

In [96]:
# 4. Fill Description nulls
df_clean['Description'] = df_clean['Description'].fillna('Unknown Product')

In [97]:
#Save the Cleaned Data

In [98]:
df_clean.to_csv("D:/DATA ANALYSIS/E-commerce Funnel & RFM/Data/cleaned/online_retail_clean.csv", index=False)

print("Saved: online_retail_clean.csv")
print(f"File size: {df_clean.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

Saved: online_retail_clean.csv
File size: 218.62 MB